// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaCX-XTOGx3-ED1EsbE1zywodQULDCp1w',
    appId: '1:217888280752:web:7fbfd02459b40c18abab75',
    messagingSenderId: '217888280752',
    projectId: 'sewabook-2acb2',
    authDomain: 'sewabook-2acb2.firebaseapp.com',
    storageBucket: 'sewabook-2acb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvrzAowzKhSSt4asJqpjJBhtaJKD4_O0',
    appId: '1:217888280752:android:134888c82b8cf7ecabab75',
    messagingSenderId: '217888280752',
    projectId: 'sewabook-2acb2',
    storageBucket: 'sewabook-2acb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsZ3bOyl_rYPPicGce-0w-nwr2R7aKsY',
    appId: '1:217888280752:ios:e7fdaba1653fcddfabab75',
    messagingSenderId: '217888280752',
    projectId: 'sewabook-2acb2',
    storageBucket: 'sewabook-2acb2.firebasestorage.app',
    iosBundleId: 'com.example.sewabook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzsZ3bOyl_rYPPicGce-0w-nwr2R7aKsY',
    appId: '1:217888280752:ios:e7fdaba1653fcddfabab75',
    messagingSenderId: '217888280752',
    projectId: 'sewabook-2acb2',
    storageBucket: 'sewabook-2acb2.firebasestorage.app',
    iosBundleId: 'com.example.sewabook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaCX-XTOGx3-ED1EsbE1zywodQULDCp1w',
    appId: '1:217888280752:web:34c9ece52b3b4585abab75',
    messagingSenderId: '217888280752',
    projectId: 'sewabook-2acb2',
    authDomain: 'sewabook-2acb2.firebaseapp.com',
    storageBucket: 'sewabook-2acb2.firebasestorage.app',
  );
}
